# ==============================================================================
# Script: Basic Inflation Model & Macroeconomic Growth Variables
# Description: Data transformation (logs and differences) and baseline 
#              Ordinary Least Squares (OLS) AR(1) modeling for CPI Inflation.
# ==============================================================================

# Load essential data manipulation libraries
library(dplyr)
library(readr)

# ------------------------------------------------------------------------------
# 1. Data Import
# ------------------------------------------------------------------------------
# Load the raw dataset
# (Update the file path to match your repository structure)
df <- read_csv("data/pakistan_macro_data.csv")

# ------------------------------------------------------------------------------
# 2. Data Transformations
# ------------------------------------------------------------------------------
df_transformed <- df %>%
  # Sort by year/date to ensure lags calculate correctly
  arrange(Year) %>%
  
  mutate(
    # Step A: Logarithmic transformations to normalize scale and stabilize variance
    log_m2   = log(money_supply_m2),
    log_govt = log(govt_expenditure),
    log_ex   = log(exchange_rate),
    
    # Step B: Calculate growth rates (First difference of natural logs)
    # This approximates the percentage change year-over-year
    m2_growth   = log_m2 - lag(log_m2),
    govt_growth = log_govt - lag(log_govt),
    ex_growth   = log_ex - lag(log_ex),
    
    # Step C: Create the Autoregressive AR(1) term for CPI Inflation
    # (CPI_INFLATION is assumed to be stationary at I(0), so we do not difference it)
    cpi_inflation_lag1 = lag(cpi_inflation)
  ) %>%
  
  # Drop the initial rows that contain NAs generated by the lag() functions
  na.omit()

# ------------------------------------------------------------------------------
# 3. Baseline Inflation Model Estimation
# ------------------------------------------------------------------------------
# Regressing current CPI Inflation on its own past (AR1) and the macroeconomic growth variables
basic_inflation_model <- lm(
  cpi_inflation ~ cpi_inflation_lag1 + m2_growth + govt_growth + ex_growth, 
  data = df_transformed
)

# Output the regression results
print("=== Baseline AR(1) & Growth Variables Model Summary ===")
summary(basic_inflation_model)

# ------------------------------------------------------------------------------
# 4. Extract Residuals & Export
# ------------------------------------------------------------------------------
# Store the model residuals back into the dataframe for any basic diagnostic plotting
df_transformed$model_residuals <- residuals(basic_inflation_model)

# Save the transformed dataset to a clean CSV for the repository
write_csv(df_transformed, "data/cleaned_macro_data_transformed.csv")

print("Data transformation and basic modeling complete. Cleaned dataset saved.")